version: '3.4'

services:
  frontend:
    build:
      context: ./front
    command: npm run start
    ports:
      - "4200:4200"
    restart: always

  backend:
    build:
      context: ./back
    env_file:
      - ./back/.env
    restart: always
    volumes:
      - '.:/app/back'
      - '/app/back/node_modules'
    ports:
      - "8000:8000"
    command: npm run start:dev

  mongo:
    container_name: db_container
    image: mongo
    ports:
      - "27017:27017"
    restart: always
