version: '3.4'

services:
  frontend:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - "4200:4200"
    restart: always

  backend:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env